export interface TriviaQuestion {
  question: string;
  options: [string, string, string, string]; // A, B, C, D
  answer: "A" | "B" | "C" | "D";
  category: string;
}

// Ordered list of trivia sections shown on the host's category picker.
// The `name` must match the `category` field on the questions below.
export const TRIVIA_CATEGORIES: { name: string; emoji: string }[] = [
  { name: "Family & Reunion", emoji: "👨‍👩‍👧‍👦" },
  { name: "Music", emoji: "🎵" },
  { name: "Sports", emoji: "⚽" },
  { name: "General Knowledge", emoji: "💡" },
  { name: "Movies", emoji: "🎬" },
  { name: "History", emoji: "📜" },
  { name: "Food & Drink", emoji: "🍝" },
];

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  /* ─────────────────────────── Family & Reunion ─────────────────────────── */
  { question: "What number Aversa Family Reunion is this?", options: ["12th", "13th", "14th", "15th"], answer: "C", category: "Family & Reunion" },
  { question: "Where is the 2026 reunion being held?", options: ["Hoboken, NJ", "Old Bridge, NJ", "Princeton, NJ", "Edison, NJ"], answer: "B", category: "Family & Reunion" },
  { question: "What hotel is hosting the reunion?", options: ["Marriott", "Hilton Garden Inn", "Hampton Inn", "Holiday Inn"], answer: "C", category: "Family & Reunion" },
  { question: "What is New Jersey's nickname?", options: ["The Garden State", "The Shore State", "The Pine State", "The Empire State"], answer: "A", category: "Family & Reunion" },
  { question: "What's a traditional Sunday dish at Italian-American family gatherings?", options: ["Tacos", "Sunday Gravy", "Fish and Chips", "Pierogi"], answer: "B", category: "Family & Reunion" },
  { question: "What does 'famiglia' mean in Italian?", options: ["Friend", "Family", "Festival", "Food"], answer: "B", category: "Family & Reunion" },
  { question: "What is the Italian word for 'grandmother'?", options: ["Nonna", "Zia", "Mamma", "Sorella"], answer: "A", category: "Family & Reunion" },
  { question: "Frank Sinatra was born in which New Jersey city?", options: ["Newark", "Jersey City", "Hoboken", "Trenton"], answer: "C", category: "Family & Reunion" },
  { question: "The TV show 'The Sopranos' was set in which state?", options: ["New York", "Connecticut", "New Jersey", "Pennsylvania"], answer: "C", category: "Family & Reunion" },
  { question: "What is the capital of Italy?", options: ["Milan", "Venice", "Florence", "Rome"], answer: "D", category: "Family & Reunion" },
  { question: "Italy is famously shaped like a what?", options: ["Boot", "Hat", "Glove", "Star"], answer: "A", category: "Family & Reunion" },
  { question: "Which Italian toast means 'to your health'?", options: ["Ciao", "Salute", "Prego", "Grazie"], answer: "B", category: "Family & Reunion" },

  /* ─────────────────────────────── Music ─────────────────────────────── */
  { question: "Which band recorded 'Bohemian Rhapsody'?", options: ["The Rolling Stones", "Queen", "The Who", "Led Zeppelin"], answer: "B", category: "Music" },
  { question: "Which instrument has 88 keys?", options: ["Guitar", "Piano", "Violin", "Trumpet"], answer: "B", category: "Music" },
  { question: "Who was known as the 'King of Rock and Roll'?", options: ["Chuck Berry", "Elvis Presley", "Little Richard", "Buddy Holly"], answer: "B", category: "Music" },
  { question: "'Thriller' was a hit album by which artist?", options: ["Prince", "Michael Jackson", "Stevie Wonder", "Lionel Richie"], answer: "B", category: "Music" },
  { question: "Which Italian-American crooner was famous for singing 'My Way'?", options: ["Dean Martin", "Frank Sinatra", "Tony Bennett", "Perry Como"], answer: "B", category: "Music" },
  { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: "C", category: "Music" },
  { question: "Who is often called the 'Queen of Soul'?", options: ["Diana Ross", "Aretha Franklin", "Tina Turner", "Gladys Knight"], answer: "B", category: "Music" },
  { question: "Taylor Swift got her start in which music genre?", options: ["Rock", "Country", "Jazz", "Classical"], answer: "B", category: "Music" },
  { question: "Which group sang 'Stayin' Alive'?", options: ["ABBA", "Bee Gees", "The Jackson 5", "Earth, Wind & Fire"], answer: "B", category: "Music" },
  { question: "The song 'Volare' is sung in which language?", options: ["French", "Spanish", "Italian", "Portuguese"], answer: "C", category: "Music" },
  { question: "Which instrument is played with a bow?", options: ["Flute", "Violin", "Trumpet", "Drums"], answer: "B", category: "Music" },
  { question: "Which city is known as the 'Home of Country Music'?", options: ["New Orleans", "Nashville", "Memphis", "Austin"], answer: "B", category: "Music" },
  { question: "Beyoncé was the lead singer of which group?", options: ["TLC", "Destiny's Child", "The Supremes", "Spice Girls"], answer: "B", category: "Music" },
  { question: "The Beatles came from which English city?", options: ["London", "Manchester", "Liverpool", "Birmingham"], answer: "C", category: "Music" },
  { question: "What does singing 'a cappella' mean?", options: ["With a guitar", "Without instruments", "Very loudly", "In Latin"], answer: "B", category: "Music" },
  { question: "'Sweet Caroline', a famous sing-along, is by which artist?", options: ["Neil Diamond", "Billy Joel", "Elton John", "James Taylor"], answer: "A", category: "Music" },
  { question: "Which decade is most associated with disco?", options: ["1950s", "1960s", "1970s", "1990s"], answer: "C", category: "Music" },
  { question: "Dolly Parton wrote which song that became a huge hit for Whitney Houston?", options: ["I Will Always Love You", "I Have Nothing", "Greatest Love of All", "Run to You"], answer: "A", category: "Music" },
  { question: "Which holiday song begins 'Chestnuts roasting on an open fire'?", options: ["Jingle Bells", "The Christmas Song", "White Christmas", "Let It Snow"], answer: "B", category: "Music" },
  { question: "Louis Armstrong was famous for playing which instrument?", options: ["Piano", "Trumpet", "Saxophone", "Drums"], answer: "B", category: "Music" },
  { question: "Which of these is a brass instrument?", options: ["Clarinet", "Trumpet", "Flute", "Cello"], answer: "B", category: "Music" },
  { question: "Elvis Presley earned which nickname?", options: ["The Boss", "The King", "The Voice", "Slowhand"], answer: "B", category: "Music" },
  { question: "Which famous trio sang 'Three Coins in the Fountain' era standards — known as the Rat Pack members included Sinatra, Sammy Davis Jr., and…?", options: ["Dean Martin", "Bing Crosby", "Bob Hope", "Nat King Cole"], answer: "A", category: "Music" },
  { question: "What is a group of musicians playing together commonly called?", options: ["A choir", "A band", "A cast", "A crew"], answer: "B", category: "Music" },

  /* ─────────────────────────────── Sports ─────────────────────────────── */
  { question: "How many players from each team are on a soccer field at once?", options: ["9", "10", "11", "12"], answer: "C", category: "Sports" },
  { question: "In baseball, how many strikes make an out?", options: ["2", "3", "4", "5"], answer: "B", category: "Sports" },
  { question: "The Super Bowl is the championship of which sport?", options: ["Baseball", "Basketball", "American Football", "Hockey"], answer: "C", category: "Sports" },
  { question: "A basketball shot from beyond the arc is worth how many points?", options: ["1", "2", "3", "4"], answer: "C", category: "Sports" },
  { question: "Which sport uses a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Table Tennis"], answer: "B", category: "Sports" },
  { question: "Which country has won the most men's FIFA World Cups?", options: ["Germany", "Brazil", "Italy", "Argentina"], answer: "B", category: "Sports" },
  { question: "How many holes are on a standard golf course?", options: ["9", "12", "18", "24"], answer: "C", category: "Sports" },
  { question: "In tennis, what is a score of zero called?", options: ["Nil", "Love", "Duck", "Blank"], answer: "B", category: "Sports" },
  { question: "The New York Yankees play which sport?", options: ["Basketball", "Football", "Baseball", "Hockey"], answer: "C", category: "Sports" },
  { question: "How many players from each team are on a basketball court?", options: ["4", "5", "6", "7"], answer: "B", category: "Sports" },
  { question: "Wimbledon is a famous championship in which sport?", options: ["Golf", "Tennis", "Cricket", "Rowing"], answer: "B", category: "Sports" },
  { question: "A 'hat trick' means scoring how many goals in one game?", options: ["2", "3", "4", "5"], answer: "B", category: "Sports" },
  { question: "The Stanley Cup is awarded in which sport?", options: ["Basketball", "Baseball", "Ice Hockey", "Soccer"], answer: "C", category: "Sports" },
  { question: "Muhammad Ali was a champion in which sport?", options: ["Wrestling", "Boxing", "Karate", "Judo"], answer: "B", category: "Sports" },
  { question: "The Italian national soccer team is nicknamed the…?", options: ["Azzurri", "Rossi", "Verdi", "Bianchi"], answer: "A", category: "Sports" },
  { question: "About how long is a marathon?", options: ["13 miles", "26 miles", "50 miles", "100 miles"], answer: "B", category: "Sports" },
  { question: "How many points is a touchdown worth (before the extra point)?", options: ["3", "6", "7", "2"], answer: "B", category: "Sports" },
  { question: "In which sport would you hear 'love', 'deuce', and 'ace'?", options: ["Golf", "Tennis", "Bowling", "Cricket"], answer: "B", category: "Sports" },
  { question: "How many bases are there on a baseball field?", options: ["3", "4", "5", "6"], answer: "B", category: "Sports" },
  { question: "The Tour de France is a famous race in which sport?", options: ["Running", "Cycling", "Swimming", "Sailing"], answer: "B", category: "Sports" },
  { question: "The Summer Olympics are held every how many years?", options: ["2", "3", "4", "5"], answer: "C", category: "Sports" },
  { question: "Which tennis legend has won the most Grand Slam singles titles among American women?", options: ["Venus Williams", "Serena Williams", "Billie Jean King", "Chris Evert"], answer: "B", category: "Sports" },
  { question: "A field goal in American football is worth how many points?", options: ["1", "2", "3", "6"], answer: "C", category: "Sports" },
  { question: "Boxing matches take place inside a what?", options: ["Court", "Ring", "Field", "Rink"], answer: "B", category: "Sports" },

  /* ────────────────────────── General Knowledge ────────────────────────── */
  { question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: "C", category: "General Knowledge" },
  { question: "What is the largest planet in our solar system?", options: ["Earth", "Mars", "Jupiter", "Saturn"], answer: "C", category: "General Knowledge" },
  { question: "What is the chemical symbol for water?", options: ["O2", "H2O", "CO2", "NaCl"], answer: "B", category: "General Knowledge" },
  { question: "How many colors are in a rainbow?", options: ["5", "6", "7", "8"], answer: "C", category: "General Knowledge" },
  { question: "What is the tallest animal in the world?", options: ["Elephant", "Giraffe", "Horse", "Camel"], answer: "B", category: "General Knowledge" },
  { question: "Which planet is known as the Red Planet?", options: ["Venus", "Saturn", "Jupiter", "Mars"], answer: "D", category: "General Knowledge" },
  { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: "B", category: "General Knowledge" },
  { question: "What is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], answer: "D", category: "General Knowledge" },
  { question: "What gas do plants absorb from the air?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], answer: "B", category: "General Knowledge" },
  { question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], answer: "B", category: "General Knowledge" },
  { question: "What is the hardest natural substance on Earth?", options: ["Gold", "Iron", "Diamond", "Quartz"], answer: "C", category: "General Knowledge" },
  { question: "Which language has the most native speakers in the world?", options: ["English", "Spanish", "Mandarin Chinese", "Hindi"], answer: "C", category: "General Knowledge" },
  { question: "How many stripes are on the American flag?", options: ["12", "13", "14", "15"], answer: "B", category: "General Knowledge" },
  { question: "What is the largest country in the world by land area?", options: ["Canada", "China", "United States", "Russia"], answer: "D", category: "General Knowledge" },
  { question: "What do bees produce?", options: ["Milk", "Honey", "Silk", "Butter"], answer: "B", category: "General Knowledge" },
  { question: "The Great Wall is located in which country?", options: ["Japan", "China", "India", "Korea"], answer: "B", category: "General Knowledge" },
  { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], answer: "B", category: "General Knowledge" },
  { question: "What currency is used in Italy and most of Europe?", options: ["Dollar", "Pound", "Euro", "Lira"], answer: "C", category: "General Knowledge" },
  { question: "What is the freezing point of water in Fahrenheit?", options: ["0°", "32°", "100°", "212°"], answer: "B", category: "General Knowledge" },
  { question: "Which is commonly cited as the longest river in the world?", options: ["Amazon", "Nile", "Mississippi", "Yangtze"], answer: "B", category: "General Knowledge" },
  { question: "How many zeros are in one million?", options: ["3", "6", "9", "12"], answer: "B", category: "General Knowledge" },
  { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: "C", category: "General Knowledge" },
  { question: "Which is the smallest U.S. state by area?", options: ["Delaware", "Rhode Island", "Connecticut", "Hawaii"], answer: "B", category: "General Knowledge" },
  { question: "What organ pumps blood through the body?", options: ["Lungs", "Brain", "Heart", "Liver"], answer: "C", category: "General Knowledge" },

  /* ─────────────────────────────── Movies ─────────────────────────────── */
  { question: "Which movie features a young lion named Simba?", options: ["The Jungle Book", "The Lion King", "Madagascar", "Tarzan"], answer: "B", category: "Movies" },
  { question: "'May the Force be with you' is a famous line from which franchise?", options: ["Star Trek", "Star Wars", "Avatar", "Guardians of the Galaxy"], answer: "B", category: "Movies" },
  { question: "Which animated film features a snowman named Olaf?", options: ["Frozen", "Tangled", "Moana", "Encanto"], answer: "A", category: "Movies" },
  { question: "The Godfather films center on what kind of family?", options: ["Royal", "Mafia", "Farming", "Circus"], answer: "B", category: "Movies" },
  { question: "Which superhero is known as the 'Caped Crusader'?", options: ["Superman", "Batman", "Spider-Man", "Iron Man"], answer: "B", category: "Movies" },
  { question: "In 'Toy Story', what kind of toy is Woody?", options: ["Astronaut", "Cowboy", "Dinosaur", "Robot"], answer: "B", category: "Movies" },
  { question: "Who played the title role in 'Forrest Gump'?", options: ["Tom Hanks", "Tom Cruise", "Kevin Costner", "Robin Williams"], answer: "A", category: "Movies" },
  { question: "In 'Finding Nemo', what kind of fish is Nemo?", options: ["Goldfish", "Clownfish", "Shark", "Tuna"], answer: "B", category: "Movies" },
  { question: "Which film series features a wizard boy named Harry?", options: ["Lord of the Rings", "Harry Potter", "Narnia", "Percy Jackson"], answer: "B", category: "Movies" },
  { question: "In 'Jaws', what animal terrorizes the beach town?", options: ["Octopus", "Shark", "Whale", "Crocodile"], answer: "B", category: "Movies" },
  { question: "Rocky Balboa is a fictional what?", options: ["Boxer", "Wrestler", "Race car driver", "Cowboy"], answer: "A", category: "Movies" },
  { question: "Which blockbuster features a ship that strikes an iceberg?", options: ["Titanic", "Poseidon", "The Perfect Storm", "Pirates of the Caribbean"], answer: "A", category: "Movies" },
  { question: "What color is the ogre Shrek?", options: ["Green", "Blue", "Purple", "Orange"], answer: "A", category: "Movies" },
  { question: "'I'll be back' is a catchphrase from which actor's films?", options: ["Arnold Schwarzenegger", "Sylvester Stallone", "Bruce Willis", "Clint Eastwood"], answer: "A", category: "Movies" },
  { question: "Mary Poppins famously arrives by what?", options: ["Train", "Umbrella", "Car", "Boat"], answer: "B", category: "Movies" },
  { question: "Which director is behind 'E.T.', 'Jaws', and 'Jurassic Park'?", options: ["Steven Spielberg", "George Lucas", "Martin Scorsese", "James Cameron"], answer: "A", category: "Movies" },
  { question: "Which animation studio made 'Toy Story' and 'Up'?", options: ["DreamWorks", "Pixar", "Warner Bros", "Illumination"], answer: "B", category: "Movies" },
  { question: "In Willy Wonka's factory, what is made?", options: ["Toys", "Chocolate", "Cars", "Shoes"], answer: "B", category: "Movies" },
  { question: "Which Disney character is a wooden boy whose nose grows when he lies?", options: ["Peter Pan", "Pinocchio", "Aladdin", "Mowgli"], answer: "B", category: "Movies" },
  { question: "The 'Fast & Furious' movies are mostly about what?", options: ["Cooking", "Street racing", "Sailing", "Flying"], answer: "B", category: "Movies" },
  { question: "Which classic film features the line 'Frankly, my dear, I don't give a damn'?", options: ["Casablanca", "Gone with the Wind", "Citizen Kane", "The Wizard of Oz"], answer: "B", category: "Movies" },
  { question: "Which holiday movie features a boy named Kevin left 'Home Alone'?", options: ["Elf", "Home Alone", "The Santa Clause", "Jingle All the Way"], answer: "B", category: "Movies" },
  { question: "In 'The Wizard of Oz', Dorothy follows a road of what color?", options: ["Red", "Silver", "Yellow", "Gold"], answer: "C", category: "Movies" },
  { question: "Which movie features a friendly alien who wants to 'phone home'?", options: ["E.T.", "Men in Black", "Alien", "Close Encounters"], answer: "A", category: "Movies" },

  /* ─────────────────────────────── History ─────────────────────────────── */
  { question: "Who was the first President of the United States?", options: ["Abraham Lincoln", "George Washington", "Thomas Jefferson", "John Adams"], answer: "B", category: "History" },
  { question: "In what year did the U.S. declare its independence?", options: ["1776", "1789", "1812", "1865"], answer: "A", category: "History" },
  { question: "Which ancient civilization built the pyramids of Giza?", options: ["Romans", "Greeks", "Egyptians", "Aztecs"], answer: "C", category: "History" },
  { question: "In which year did the Titanic sink?", options: ["1905", "1912", "1918", "1923"], answer: "B", category: "History" },
  { question: "Who was U.S. President during the Civil War?", options: ["Washington", "Lincoln", "Roosevelt", "Jefferson"], answer: "B", category: "History" },
  { question: "Which country gifted the Statue of Liberty to the United States?", options: ["England", "France", "Spain", "Italy"], answer: "B", category: "History" },
  { question: "Who is credited with reaching the Americas in 1492, sailing for Spain?", options: ["Magellan", "Christopher Columbus", "Amerigo Vespucci", "Hernán Cortés"], answer: "B", category: "History" },
  { question: "In which year did World War II end?", options: ["1939", "1942", "1945", "1950"], answer: "C", category: "History" },
  { question: "Who delivered the famous 'I Have a Dream' speech?", options: ["Malcolm X", "Martin Luther King Jr.", "John F. Kennedy", "Rosa Parks"], answer: "B", category: "History" },
  { question: "Which wall famously fell in 1989?", options: ["The Great Wall", "The Berlin Wall", "Hadrian's Wall", "Wall Street"], answer: "B", category: "History" },
  { question: "The Roman Empire was centered in which modern-day country?", options: ["Greece", "Italy", "Egypt", "Spain"], answer: "B", category: "History" },
  { question: "Who was the first man to walk on the Moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin", "John Glenn"], answer: "B", category: "History" },
  { question: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], answer: "B", category: "History" },
  { question: "Who served as British Prime Minister through most of World War II?", options: ["Winston Churchill", "Tony Blair", "Margaret Thatcher", "Neville Chamberlain"], answer: "A", category: "History" },
  { question: "The ancient city of Pompeii was buried by a volcano in which country?", options: ["Greece", "Italy", "Turkey", "Egypt"], answer: "B", category: "History" },
  { question: "Which queen reigned over the United Kingdom for over 70 years until 2022?", options: ["Elizabeth I", "Victoria", "Elizabeth II", "Mary"], answer: "C", category: "History" },
  { question: "The American Revolution was a war for independence from which country?", options: ["France", "Spain", "Britain", "Germany"], answer: "C", category: "History" },
  { question: "Ancient Rome was said to be built upon how many hills?", options: ["5", "7", "9", "12"], answer: "B", category: "History" },
  { question: "The Declaration of Independence was signed in which city?", options: ["New York", "Philadelphia", "Boston", "Washington, D.C."], answer: "B", category: "History" },
  { question: "Whose expedition was the first to sail all the way around the world?", options: ["Columbus", "Magellan", "Drake", "Cook"], answer: "B", category: "History" },
  { question: "The ancient Olympic Games began in which country?", options: ["Italy", "Greece", "Egypt", "China"], answer: "B", category: "History" },
  { question: "Which U.S. President is featured on the one-dollar bill?", options: ["Lincoln", "Washington", "Jefferson", "Franklin"], answer: "B", category: "History" },
  { question: "Who was the famous founder of modern nursing during the Crimean War?", options: ["Clara Barton", "Florence Nightingale", "Mother Teresa", "Joan of Arc"], answer: "B", category: "History" },
  { question: "The Egyptian pyramids were built primarily as what?", options: ["Temples", "Tombs", "Palaces", "Markets"], answer: "B", category: "History" },

  /* ────────────────────────────── Food & Drink ────────────────────────────── */
  { question: "Which country is credited with inventing pizza?", options: ["France", "Italy", "Greece", "Spain"], answer: "B", category: "Food & Drink" },
  { question: "What is the main ingredient in guacamole?", options: ["Tomato", "Avocado", "Pepper", "Onion"], answer: "B", category: "Food & Drink" },
  { question: "Parmesan cheese originally comes from which country?", options: ["France", "Italy", "Switzerland", "Greece"], answer: "B", category: "Food & Drink" },
  { question: "Espresso is a strong type of what?", options: ["Tea", "Coffee", "Juice", "Soda"], answer: "B", category: "Food & Drink" },
  { question: "Which pasta is long and thin?", options: ["Penne", "Spaghetti", "Ravioli", "Lasagna"], answer: "B", category: "Food & Drink" },
  { question: "Which fruit is used to make wine?", options: ["Apple", "Grape", "Orange", "Cherry"], answer: "B", category: "Food & Drink" },
  { question: "Tiramisu is a dessert that originated in which country?", options: ["France", "Italy", "Austria", "Greece"], answer: "B", category: "Food & Drink" },
  { question: "Which spice is the most expensive in the world by weight?", options: ["Black pepper", "Saffron", "Cinnamon", "Vanilla"], answer: "B", category: "Food & Drink" },
  { question: "Mozzarella is traditionally made from the milk of which animals (in Italy)?", options: ["Cow or buffalo", "Goat", "Sheep", "Camel"], answer: "A", category: "Food & Drink" },
  { question: "Sushi originated in which country?", options: ["China", "Japan", "Korea", "Thailand"], answer: "B", category: "Food & Drink" },
  { question: "Which nut is traditionally used to make pesto?", options: ["Walnut", "Pine nut", "Almond", "Cashew"], answer: "B", category: "Food & Drink" },
  { question: "Cannoli are a dessert traditionally from which Italian region?", options: ["Tuscany", "Sicily", "Veneto", "Lombardy"], answer: "B", category: "Food & Drink" },
  { question: "Which of these is an Italian cured meat?", options: ["Prosciutto", "Baguette", "Croissant", "Tortilla"], answer: "A", category: "Food & Drink" },
  { question: "What ingredient makes bread rise?", options: ["Yeast", "Salt", "Sugar", "Butter"], answer: "A", category: "Food & Drink" },
  { question: "Gelato is the Italian version of what?", options: ["Cake", "Ice cream", "Pudding", "Pie"], answer: "B", category: "Food & Drink" },
  { question: "Which herb tops a classic Margherita pizza?", options: ["Basil", "Mint", "Rosemary", "Dill"], answer: "A", category: "Food & Drink" },
  { question: "Risotto is made primarily from what?", options: ["Pasta", "Rice", "Potatoes", "Beans"], answer: "B", category: "Food & Drink" },
  { question: "What is the main ingredient in traditional hummus?", options: ["Chickpeas", "Lentils", "Black beans", "Peas"], answer: "A", category: "Food & Drink" },
  { question: "Which country is famous for inventing the croissant's homeland pastries?", options: ["Italy", "France", "Germany", "Spain"], answer: "B", category: "Food & Drink" },
  { question: "Butter is made by churning what?", options: ["Milk", "Cream", "Yogurt", "Cheese"], answer: "B", category: "Food & Drink" },
  { question: "What vegetable is fermented to make sauerkraut?", options: ["Lettuce", "Cabbage", "Spinach", "Kale"], answer: "B", category: "Food & Drink" },
  { question: "What is the main ingredient in an omelette?", options: ["Eggs", "Cheese", "Potatoes", "Flour"], answer: "A", category: "Food & Drink" },
  { question: "Which drink is made from roasted, ground beans?", options: ["Tea", "Coffee", "Lemonade", "Cider"], answer: "B", category: "Food & Drink" },
  { question: "'Parmigiano-Reggiano' is often called the 'King of' what?", options: ["Breads", "Cheeses", "Wines", "Pastas"], answer: "B", category: "Food & Drink" },
];
